/* ─── catalog-data.js — 60 real AI tools ── */

const CATALOG = [

  /* ── General AI Chat ───────────────────────────────────────── */
  {
    id: 'chatgpt',
    name: 'ChatGPT',
    category: 'General AI Chat',
    costLabel: '$20/mo',
    cost: 20,
    description: 'OpenAI\'s flagship conversational AI with GPT-4o, image generation, and a plugin ecosystem.',
    features: ['GPT-4o access', 'DALL-E image gen', 'Code interpreter', 'Custom GPTs'],
    website: 'chat.openai.com',
    tags: ['chat', 'writing', 'coding', 'images', 'openai'],
  },
  {
    id: 'claude',
    name: 'Claude',
    category: 'General AI Chat',
    costLabel: '$20/mo',
    cost: 20,
    description: 'Anthropic\'s AI assistant known for long context, nuanced reasoning, and safe outputs.',
    features: ['200K context window', 'Document analysis', 'Advanced reasoning', 'Projects memory'],
    website: 'claude.ai',
    tags: ['chat', 'writing', 'analysis', 'long-context', 'anthropic'],
  },
  {
    id: 'gemini',
    name: 'Gemini Advanced',
    category: 'General AI Chat',
    costLabel: '$20/mo',
    cost: 20,
    description: 'Google\'s multimodal AI integrated with Workspace, YouTube, and Google Search.',
    features: ['Gemini 1.5 Pro', 'Google integration', 'Multimodal', '1M context window'],
    website: 'gemini.google.com',
    tags: ['chat', 'google', 'multimodal', 'workspace'],
  },
  {
    id: 'copilot',
    name: 'Microsoft Copilot',
    category: 'General AI Chat',
    costLabel: 'Free',
    cost: 0,
    description: 'Microsoft\'s AI assistant powered by GPT-4, integrated with Edge, Bing, and Microsoft 365.',
    features: ['GPT-4 powered', 'Web search', 'Image generation', 'Free tier'],
    website: 'copilot.microsoft.com',
    tags: ['chat', 'microsoft', 'free', 'search'],
  },
  {
    id: 'perplexity',
    name: 'Perplexity AI',
    category: 'General AI Chat',
    costLabel: '$20/mo',
    cost: 20,
    description: 'Conversational AI with real-time web search that cites its sources on every answer.',
    features: ['Real-time search', 'Source citations', 'Pro search mode', 'File upload'],
    website: 'perplexity.ai',
    tags: ['chat', 'search', 'research', 'citations'],
  },
  {
    id: 'grok',
    name: 'Grok',
    category: 'General AI Chat',
    costLabel: '$16/mo',
    cost: 16,
    description: 'xAI\'s assistant with real-time X/Twitter data access and an unfiltered conversation style.',
    features: ['Real-time X data', 'Image generation', 'Aurora image model', 'DeepSearch'],
    website: 'x.ai/grok',
    tags: ['chat', 'twitter', 'realtime', 'xai'],
  },

  /* ── Coding Assistant ───────────────────────────────────────── */
  {
    id: 'cursor',
    name: 'Cursor',
    category: 'Coding Assistant',
    costLabel: '$20/mo',
    cost: 20,
    description: 'AI-first code editor built on VS Code with codebase-aware chat, autocomplete, and agent mode.',
    features: ['Codebase context', 'Agent mode', 'Multi-file edits', 'Claude & GPT-4 models'],
    website: 'cursor.com',
    tags: ['coding', 'editor', 'autocomplete', 'vscode'],
  },
  {
    id: 'github-copilot',
    name: 'GitHub Copilot',
    category: 'Coding Assistant',
    costLabel: '$10/mo',
    cost: 10,
    description: 'GitHub\'s AI pair programmer that suggests code inline and answers questions about your repo.',
    features: ['Inline suggestions', 'Chat in IDE', 'PR summaries', 'CLI support'],
    website: 'github.com/features/copilot',
    tags: ['coding', 'github', 'autocomplete', 'vscode'],
  },
  {
    id: 'windsurf',
    name: 'Windsurf',
    category: 'Coding Assistant',
    costLabel: '$15/mo',
    cost: 15,
    description: 'Codeium\'s agentic IDE that can autonomously plan, write, and debug multi-file changes.',
    features: ['Cascade agent', 'Multi-file edits', 'Terminal access', 'Codebase search'],
    website: 'codeium.com/windsurf',
    tags: ['coding', 'editor', 'agent', 'codeium'],
  },
  {
    id: 'claude-code',
    name: 'Claude Code',
    category: 'Coding Assistant',
    costLabel: '$20/mo',
    cost: 20,
    description: 'Anthropic\'s agentic CLI tool that reads, writes, and runs code directly in your terminal.',
    features: ['Terminal-native', 'Full repo access', 'Git integration', 'MCP support'],
    website: 'claude.ai/code',
    tags: ['coding', 'cli', 'agent', 'anthropic'],
  },
  {
    id: 'tabnine',
    name: 'Tabnine',
    category: 'Coding Assistant',
    costLabel: '$12/mo',
    cost: 12,
    description: 'AI code completion tool focused on privacy with on-premise and private cloud deployment options.',
    features: ['Private deployment', 'Team learning', 'Multi-IDE', 'Code review'],
    website: 'tabnine.com',
    tags: ['coding', 'autocomplete', 'privacy', 'enterprise'],
  },
  {
    id: 'replit-ai',
    name: 'Replit AI',
    category: 'Coding Assistant',
    costLabel: '$25/mo',
    cost: 25,
    description: 'AI coding assistant built into Replit\'s browser IDE with full deployment and hosting.',
    features: ['Browser IDE', 'One-click deploy', 'AI chat', 'Collaborative'],
    website: 'replit.com',
    tags: ['coding', 'browser', 'deploy', 'hosting'],
  },

  /* ── Writing & Content ──────────────────────────────────────── */
  {
    id: 'jasper',
    name: 'Jasper',
    category: 'Writing & Content',
    costLabel: '$49/mo',
    cost: 49,
    description: 'Enterprise AI writing platform with brand voice controls, templates, and marketing workflows.',
    features: ['Brand voice', '50+ templates', 'SEO mode', 'Team collaboration'],
    website: 'jasper.ai',
    tags: ['writing', 'marketing', 'content', 'brand'],
  },
  {
    id: 'copy-ai',
    name: 'Copy.ai',
    category: 'Writing & Content',
    costLabel: '$49/mo',
    cost: 49,
    description: 'AI writing assistant focused on marketing copy, sales emails, and content workflows.',
    features: ['100+ templates', 'Workflows', 'Brand voice', 'Bulk generation'],
    website: 'copy.ai',
    tags: ['writing', 'marketing', 'copy', 'sales'],
  },
  {
    id: 'grammarly',
    name: 'Grammarly',
    category: 'Writing & Content',
    costLabel: '$30/mo',
    cost: 30,
    description: 'AI writing assistant that catches grammar, tone, clarity, and style issues across apps.',
    features: ['Grammar check', 'Tone detection', 'Browser extension', 'Plagiarism check'],
    website: 'grammarly.com',
    tags: ['writing', 'grammar', 'editing', 'browser'],
  },
  {
    id: 'notion-ai',
    name: 'Notion AI',
    category: 'Writing & Content',
    costLabel: '$10/mo',
    cost: 10,
    description: 'AI writing and summarization built natively into Notion docs, databases, and wikis.',
    features: ['In-doc generation', 'Summarize pages', 'Q&A on workspace', 'Autofill tables'],
    website: 'notion.so/product/ai',
    tags: ['writing', 'notes', 'notion', 'summarize'],
  },
  {
    id: 'writesonic',
    name: 'Writesonic',
    category: 'Writing & Content',
    costLabel: '$20/mo',
    cost: 20,
    description: 'AI writer for blog posts, ads, product descriptions, and landing pages with SEO optimization.',
    features: ['SEO articles', 'Ad copy', 'AI chatbot builder', 'Factual mode'],
    website: 'writesonic.com',
    tags: ['writing', 'seo', 'blog', 'ads'],
  },
  {
    id: 'sudowrite',
    name: 'Sudowrite',
    category: 'Writing & Content',
    costLabel: '$19/mo',
    cost: 19,
    description: 'AI writing tool built specifically for fiction authors — story development, brainstorming, and prose.',
    features: ['Story Bible', 'Write mode', 'Describe tool', 'Canvas view'],
    website: 'sudowrite.com',
    tags: ['writing', 'fiction', 'creative', 'storytelling'],
  },

  /* ── Image Generation ───────────────────────────────────────── */
  {
    id: 'midjourney',
    name: 'Midjourney',
    category: 'Image Generation',
    costLabel: '$10/mo',
    cost: 10,
    description: 'The leading AI image generator known for stunning artistic quality and photorealistic renders.',
    features: ['V7 model', 'Vary & remix', 'Style tuning', 'High-res upscale'],
    website: 'midjourney.com',
    tags: ['images', 'art', 'design', 'creative'],
  },
  {
    id: 'dalle3',
    name: 'DALL-E 3',
    category: 'Image Generation',
    costLabel: '$20/mo',
    cost: 20,
    description: 'OpenAI\'s image model integrated into ChatGPT with accurate text rendering and prompt following.',
    features: ['Text accuracy', 'ChatGPT integration', 'Consistent style', 'API access'],
    website: 'openai.com/dall-e-3',
    tags: ['images', 'openai', 'text-in-image'],
  },
  {
    id: 'stable-diffusion',
    name: 'Stable Diffusion',
    category: 'Image Generation',
    costLabel: 'Free',
    cost: 0,
    description: 'Open-source image generation model runnable locally or via platforms like Automatic1111.',
    features: ['Open source', 'Run locally', 'Fine-tuning', 'LoRA models'],
    website: 'stability.ai',
    tags: ['images', 'open-source', 'local', 'free'],
  },
  {
    id: 'ideogram',
    name: 'Ideogram',
    category: 'Image Generation',
    costLabel: '$8/mo',
    cost: 8,
    description: 'AI image tool with best-in-class text rendering in images and strong typography support.',
    features: ['Text in images', 'Typography', 'Realism mode', 'Free tier'],
    website: 'ideogram.ai',
    tags: ['images', 'text', 'typography', 'design'],
  },
  {
    id: 'adobe-firefly',
    name: 'Adobe Firefly',
    category: 'Image Generation',
    costLabel: '$5/mo',
    cost: 5,
    description: 'Adobe\'s commercially safe AI image generator trained on licensed content and integrated with Creative Cloud.',
    features: ['Commercially safe', 'Photoshop integration', 'Generative fill', 'Style reference'],
    website: 'firefly.adobe.com',
    tags: ['images', 'adobe', 'commercial', 'design'],
  },
  {
    id: 'leonardo-ai',
    name: 'Leonardo AI',
    category: 'Image Generation',
    costLabel: '$12/mo',
    cost: 12,
    description: 'Game-asset-focused AI image platform with fine-tuned models, canvas, and video generation.',
    features: ['Game assets', 'Fine-tuned models', 'Canvas editor', 'Video gen'],
    website: 'leonardo.ai',
    tags: ['images', 'games', 'assets', 'design'],
  },

  /* ── Video Creation ─────────────────────────────────────────── */
  {
    id: 'runway',
    name: 'Runway',
    category: 'Video Creation',
    costLabel: '$15/mo',
    cost: 15,
    description: 'Professional AI video editor with Gen-3 text-to-video, inpainting, and motion brush tools.',
    features: ['Gen-3 video', 'Motion brush', 'Green screen', 'Background removal'],
    website: 'runwayml.com',
    tags: ['video', 'editing', 'generation', 'creative'],
  },
  {
    id: 'sora',
    name: 'Sora',
    category: 'Video Creation',
    costLabel: '$20/mo',
    cost: 20,
    description: 'OpenAI\'s text-to-video model generating cinematic, high-fidelity clips up to 20 seconds.',
    features: ['Up to 20s clips', '1080p output', 'Storyboard mode', 'Remix existing video'],
    website: 'sora.com',
    tags: ['video', 'openai', 'text-to-video', 'cinematic'],
  },
  {
    id: 'heygen',
    name: 'HeyGen',
    category: 'Video Creation',
    costLabel: '$29/mo',
    cost: 29,
    description: 'AI video generator for creating talking-head presenter videos with digital avatars and voice cloning.',
    features: ['AI avatars', 'Voice cloning', '175 languages', 'Custom avatar'],
    website: 'heygen.com',
    tags: ['video', 'avatar', 'presenter', 'voice'],
  },
  {
    id: 'pika',
    name: 'Pika',
    category: 'Video Creation',
    costLabel: '$8/mo',
    cost: 8,
    description: 'Fast text-to-video and image-to-video AI with a simple interface and Discord community.',
    features: ['Text-to-video', 'Image-to-video', 'Lip sync', 'Pikaffects'],
    website: 'pika.art',
    tags: ['video', 'generation', 'image-to-video', 'fast'],
  },
  {
    id: 'synthesia',
    name: 'Synthesia',
    category: 'Video Creation',
    costLabel: '$29/mo',
    cost: 29,
    description: 'Enterprise AI video platform for creating training and explainer videos with lifelike avatars.',
    features: ['160+ avatars', 'Screen recorder', 'SCORM export', 'Brand kit'],
    website: 'synthesia.io',
    tags: ['video', 'enterprise', 'training', 'avatar'],
  },

  /* ── Audio & Transcription ──────────────────────────────────── */
  {
    id: 'whisper',
    name: 'Whisper (OpenAI)',
    category: 'Audio & Transcription',
    costLabel: 'Free',
    cost: 0,
    description: 'OpenAI\'s open-source speech recognition model with best-in-class accuracy across 100+ languages.',
    features: ['100+ languages', 'Open source', 'Local run', 'API access'],
    website: 'openai.com/research/whisper',
    tags: ['audio', 'transcription', 'open-source', 'speech'],
  },
  {
    id: 'otter-ai',
    name: 'Otter.ai',
    category: 'Audio & Transcription',
    costLabel: '$17/mo',
    cost: 17,
    description: 'Real-time meeting transcription with speaker identification, summaries, and Zoom/Teams integration.',
    features: ['Real-time transcript', 'Speaker ID', 'Meeting summary', 'Zoom integration'],
    website: 'otter.ai',
    tags: ['audio', 'meetings', 'transcription', 'zoom'],
  },
  {
    id: 'eleven-labs',
    name: 'ElevenLabs',
    category: 'Audio & Transcription',
    costLabel: '$22/mo',
    cost: 22,
    description: 'AI voice synthesis platform for text-to-speech, voice cloning, and dubbing in 30+ languages.',
    features: ['Voice cloning', 'Text-to-speech', 'Dubbing', '30+ languages'],
    website: 'elevenlabs.io',
    tags: ['audio', 'voice', 'tts', 'cloning'],
  },
  {
    id: 'descript',
    name: 'Descript',
    category: 'Audio & Transcription',
    costLabel: '$24/mo',
    cost: 24,
    description: 'All-in-one podcast and video editor where you edit audio/video by editing the transcript text.',
    features: ['Edit by transcript', 'Overdub voice', 'Screen recorder', 'Studio Sound'],
    website: 'descript.com',
    tags: ['audio', 'video', 'podcast', 'editing'],
  },
  {
    id: 'fireflies',
    name: 'Fireflies.ai',
    category: 'Audio & Transcription',
    costLabel: '$18/mo',
    cost: 18,
    description: 'AI meeting assistant that joins calls, transcribes, and generates action items and summaries.',
    features: ['Auto-join calls', 'Action items', 'Search transcripts', 'CRM sync'],
    website: 'fireflies.ai',
    tags: ['audio', 'meetings', 'crm', 'notes'],
  },

  /* ── Research & Search ──────────────────────────────────────── */
  {
    id: 'perplexity-pro',
    name: 'Perplexity Pro',
    category: 'Research & Search',
    costLabel: '$20/mo',
    cost: 20,
    description: 'AI-powered answer engine with real-time web access, deep research mode, and source citations.',
    features: ['Deep research', 'Source citations', 'Multiple models', 'Pro search'],
    website: 'perplexity.ai',
    tags: ['research', 'search', 'citations', 'realtime'],
  },
  {
    id: 'elicit',
    name: 'Elicit',
    category: 'Research & Search',
    costLabel: '$12/mo',
    cost: 12,
    description: 'AI research assistant that finds, reads, and synthesizes academic papers from 125M+ sources.',
    features: ['125M papers', 'Data extraction', 'Synthesis', 'Citation export'],
    website: 'elicit.com',
    tags: ['research', 'academic', 'papers', 'literature'],
  },
  {
    id: 'consensus',
    name: 'Consensus',
    category: 'Research & Search',
    costLabel: '$11/mo',
    cost: 11,
    description: 'Search engine that pulls consensus from scientific literature and summarizes findings with citations.',
    features: ['Scientific consensus', 'Paper summaries', 'GPT-4 synthesis', 'Citation links'],
    website: 'consensus.app',
    tags: ['research', 'science', 'academic', 'consensus'],
  },
  {
    id: 'you-research',
    name: 'You.com Research',
    category: 'Research & Search',
    costLabel: '$15/mo',
    cost: 15,
    description: 'AI search and research platform with multi-step research agents and real-time web data.',
    features: ['Research agent', 'Real-time web', 'Multi-model', 'Code mode'],
    website: 'you.com',
    tags: ['research', 'search', 'agent', 'realtime'],
  },
  {
    id: 'scholarai',
    name: 'ScholarAI',
    category: 'Research & Search',
    costLabel: '$10/mo',
    cost: 10,
    description: 'ChatGPT plugin and standalone tool for searching peer-reviewed papers and generating literature reviews.',
    features: ['Peer-reviewed only', 'Literature review', 'Citation generation', 'PDF reader'],
    website: 'scholarai.io',
    tags: ['research', 'academic', 'papers', 'chatgpt'],
  },

  /* ── Productivity & Notes ───────────────────────────────────── */
  {
    id: 'notion',
    name: 'Notion',
    category: 'Productivity & Notes',
    costLabel: '$16/mo',
    cost: 16,
    description: 'All-in-one workspace for notes, wikis, databases, and project management with built-in AI.',
    features: ['Docs & wikis', 'Databases', 'AI writing', 'Team collaboration'],
    website: 'notion.so',
    tags: ['notes', 'productivity', 'wiki', 'project-management'],
  },
  {
    id: 'mem',
    name: 'Mem',
    category: 'Productivity & Notes',
    costLabel: '$14/mo',
    cost: 14,
    description: 'AI-first note-taking app that auto-organizes notes and lets you chat with your entire knowledge base.',
    features: ['Auto-organize', 'Chat with notes', 'Smart search', 'No folders needed'],
    website: 'mem.ai',
    tags: ['notes', 'ai', 'knowledge', 'search'],
  },
  {
    id: 'obsidian',
    name: 'Obsidian',
    category: 'Productivity & Notes',
    costLabel: 'Free',
    cost: 0,
    description: 'Local-first markdown note-taking app with a knowledge graph and a growing AI plugin ecosystem.',
    features: ['Knowledge graph', 'Local storage', 'Plugins', 'Markdown'],
    website: 'obsidian.md',
    tags: ['notes', 'markdown', 'local', 'knowledge-graph'],
  },
  {
    id: 'reclaim-ai',
    name: 'Reclaim.ai',
    category: 'Productivity & Notes',
    costLabel: '$10/mo',
    cost: 10,
    description: 'AI calendar scheduling tool that automatically blocks focus time and schedules tasks around meetings.',
    features: ['Auto-scheduling', 'Focus time', 'Habit blocks', 'Slack integration'],
    website: 'reclaim.ai',
    tags: ['productivity', 'calendar', 'scheduling', 'time'],
  },
  {
    id: 'motion',
    name: 'Motion',
    category: 'Productivity & Notes',
    costLabel: '$34/mo',
    cost: 34,
    description: 'AI project and task manager that auto-schedules your entire work day and reschedules when plans change.',
    features: ['Auto-schedule', 'Task priority', 'Project planning', 'Calendar sync'],
    website: 'usemotion.com',
    tags: ['productivity', 'tasks', 'scheduling', 'project'],
  },

  /* ── SEO & Marketing ────────────────────────────────────────── */
  {
    id: 'surfer-seo',
    name: 'Surfer SEO',
    category: 'SEO & Marketing',
    costLabel: '$89/mo',
    cost: 89,
    description: 'AI content editor that analyzes top-ranking pages and tells you exactly how to optimize your content.',
    features: ['Content score', 'SERP analysis', 'NLP keywords', 'AI writer'],
    website: 'surferseo.com',
    tags: ['seo', 'content', 'optimization', 'serp'],
  },
  {
    id: 'semrush-ai',
    name: 'Semrush',
    category: 'SEO & Marketing',
    costLabel: '$140/mo',
    cost: 140,
    description: 'All-in-one SEO and marketing platform with keyword research, backlink analysis, and AI content tools.',
    features: ['Keyword research', 'Backlink audit', 'Site audit', 'AI content'],
    website: 'semrush.com',
    tags: ['seo', 'keywords', 'backlinks', 'marketing'],
  },
  {
    id: 'frase',
    name: 'Frase',
    category: 'SEO & Marketing',
    costLabel: '$15/mo',
    cost: 15,
    description: 'AI-powered content research and writing tool that creates SEO briefs and optimizes drafts.',
    features: ['SERP research', 'Content briefs', 'AI writer', 'Optimization score'],
    website: 'frase.io',
    tags: ['seo', 'content', 'briefs', 'writing'],
  },
  {
    id: 'adcreative',
    name: 'AdCreative.ai',
    category: 'SEO & Marketing',
    costLabel: '$29/mo',
    cost: 29,
    description: 'AI ad creative generator that produces high-converting banners, social ads, and product images.',
    features: ['Ad banners', 'Social creatives', 'Product photos', 'A/B testing'],
    website: 'adcreative.ai',
    tags: ['ads', 'design', 'marketing', 'banners'],
  },
  {
    id: 'brandwatch',
    name: 'Brandwatch',
    category: 'SEO & Marketing',
    costLabel: '$108/mo',
    cost: 108,
    description: 'AI-powered social listening and consumer intelligence platform for brand monitoring and trend analysis.',
    features: ['Social listening', 'Sentiment analysis', 'Trend detection', 'Influencer ID'],
    website: 'brandwatch.com',
    tags: ['marketing', 'social', 'listening', 'brand'],
  },
  {
    id: 'albert-ai',
    name: 'Mutiny',
    category: 'SEO & Marketing',
    costLabel: '$1500/mo',
    cost: 1500,
    description: 'AI-powered website personalization platform that customizes landing pages for different audiences.',
    features: ['Web personalization', 'A/B testing', 'Account targeting', 'CRM sync'],
    website: 'mutinyhq.com',
    tags: ['marketing', 'personalization', 'conversion', 'b2b'],
  },

  /* ── Data & Analytics ───────────────────────────────────────── */
  {
    id: 'julius-ai',
    name: 'Julius AI',
    category: 'Data & Analytics',
    costLabel: '$20/mo',
    cost: 20,
    description: 'Chat-based data analysis tool that reads CSV/Excel files and generates charts, stats, and insights.',
    features: ['CSV analysis', 'Chart generation', 'Python execution', 'SQL queries'],
    website: 'julius.ai',
    tags: ['data', 'analysis', 'csv', 'charts'],
  },
  {
    id: 'obviously-ai',
    name: 'Obviously AI',
    category: 'Data & Analytics',
    costLabel: '$75/mo',
    cost: 75,
    description: 'No-code AI platform that builds predictive models from your data in minutes without coding.',
    features: ['No-code ML', 'Predictive models', 'Auto-features', 'API export'],
    website: 'obviously.ai',
    tags: ['data', 'ml', 'no-code', 'predictive'],
  },
  {
    id: 'tableau-ai',
    name: 'Tableau + Einstein',
    category: 'Data & Analytics',
    costLabel: '$75/mo',
    cost: 75,
    description: 'Tableau\'s BI platform with Salesforce Einstein AI for natural language queries and predictive analytics.',
    features: ['NL queries', 'Auto visualize', 'Predictive', 'Salesforce sync'],
    website: 'tableau.com',
    tags: ['data', 'bi', 'visualization', 'salesforce'],
  },
  {
    id: 'polymer',
    name: 'Polymer',
    category: 'Data & Analytics',
    costLabel: '$20/mo',
    cost: 20,
    description: 'AI-powered spreadsheet-to-dashboard tool that turns any data file into interactive visualizations.',
    features: ['Auto dashboards', 'Natural language', 'No SQL needed', 'Share links'],
    website: 'polymersearch.com',
    tags: ['data', 'dashboards', 'spreadsheet', 'visualization'],
  },
  {
    id: 'akkio',
    name: 'Akkio',
    category: 'Data & Analytics',
    costLabel: '$49/mo',
    cost: 49,
    description: 'Business AI platform for building forecasting and classification models from spreadsheet data.',
    features: ['Forecasting', 'Classification', 'Chat with data', 'Agency tools'],
    website: 'akkio.com',
    tags: ['data', 'forecasting', 'ml', 'no-code'],
  },
  {
    id: 'rows-ai',
    name: 'Rows',
    category: 'Data & Analytics',
    costLabel: '$59/mo',
    cost: 59,
    description: 'AI-powered spreadsheet that connects to 50+ data sources and lets you analyze data with prompts.',
    features: ['AI analyst', '50+ integrations', 'Auto charts', 'Published reports'],
    website: 'rows.com',
    tags: ['data', 'spreadsheet', 'integrations', 'charts'],
  },
];
